name: lab1
version: 0.1.0.0
github: "githubuser/lab1"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2019 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/DzyubSpirit/lab1#readme>

dependencies:
  - base >= 4.7 && < 5
  - gtk3
  - protolude
  - stm
  - stm-chans
  - fgl
  - ige >= 0.3.1.10
  - microlens-platform
  - conduit
  - stm-conduit
  - mtl
  - bytestring
  - cairo
  - containers
  - hspec
  - random

library:
  source-dirs: src

executables:
  lab1-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - lab1

default-extensions:
  - NoImplicitPrelude
  - FlexibleContexts
  - NoMonomorphismRestriction
  - TypeFamilies
  - GeneralizedNewtypeDeriving
  - TemplateHaskell
  - TypeSynonymInstances
  - FlexibleInstances
  - RankNTypes
  - OverloadedStrings

tests:
  lab1-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - lab1
